# Generated by Django 3.1.1 on 2020-10-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201019_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='foto',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d/'),
        ),
    ]
