# Generated by Django 3.1.1 on 2020-10-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('endereco', models.CharField(max_length=500)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='galeria')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='galeria')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='galeria')),
                ('foto4', models.ImageField(blank=True, null=True, upload_to='galeria')),
                ('foto5', models.ImageField(blank=True, null=True, upload_to='galeria')),
                ('foto6', models.ImageField(blank=True, null=True, upload_to='galeria')),
                ('foto7', models.ImageField(blank=True, null=True, upload_to='galeria')),
                ('foto8', models.ImageField(blank=True, null=True, upload_to='galeria')),
                ('foto9', models.ImageField(blank=True, null=True, upload_to='galeria')),
                ('foto10', models.ImageField(blank=True, null=True, upload_to='galeria')),
                ('foto11', models.ImageField(blank=True, null=True, upload_to='galeria')),
                ('foto12', models.ImageField(blank=True, null=True, upload_to='galeria')),
                ('foto13', models.ImageField(blank=True, null=True, upload_to='galeria')),
                ('foto14', models.ImageField(blank=True, null=True, upload_to='galeria')),
                ('foto15', models.ImageField(blank=True, null=True, upload_to='galeria')),
                ('foto16', models.ImageField(blank=True, null=True, upload_to='galeria')),
                ('foto17', models.ImageField(blank=True, null=True, upload_to='galeria')),
                ('foto18', models.ImageField(blank=True, null=True, upload_to='galeria')),
                ('foto19', models.ImageField(blank=True, null=True, upload_to='galeria')),
                ('foto20', models.ImageField(blank=True, null=True, upload_to='galeria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
