# Generated by Django 3.1.1 on 2020-10-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_galeria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
    ]
