# Generated by Django 3.1.1 on 2020-10-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20201022_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='task',
            name='foto4',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/'),
        ),
    ]
