# Generated by Django 3.1.1 on 2020-10-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20201022_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeria',
            name='endereco',
        ),
    ]
