# Generated by Django 3.1.1 on 2021-02-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_base_conhecimento_formularios_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Nascimento',
            field=models.CharField(blank=True, help_text='Ex: Dia/Mês/Ano', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='base_conhecimento',
            name='foto',
            field=models.FileField(upload_to='Base_conhecimentos'),
        ),
        migrations.AlterField(
            model_name='formularios_db',
            name='foto',
            field=models.FileField(upload_to='formularios'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='foto',
            field=models.ImageField(upload_to='galeria'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Ramal',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
